// fixtures/button.tsx
import React from "react";

export interface ButtonProps {
  label: string;
  variant?: "primary" | "secondary" | "ghost";
  disabled?: boolean;
  onClick?: () => void;
  children?: React.ReactNode;
}

export function Button({
  label,
  variant = "primary",
  disabled = false,
  onClick,
  children,
}: ButtonProps) {
  return (
    <button
      type="button"
      className={`btn btn-${variant}`}
      disabled={disabled}
      onClick={onClick}
    >
      {children ?? label}
    </button>
  );
}

export default Button;

// fixtures/vue-project/Button.vue
<script setup lang="ts">
interface Props {
  label: string;
  variant?: "primary" | "secondary" | "danger";
  disabled?: boolean;
  count?: number;
}

const props = defineProps<Props>();
</script>

<template>
  <button class="btn" :class="props.variant" :disabled="props.disabled">
    {{ props.label }}<span v-if="props.count"> ({{ props.count }})</span>
  </button>
</template>

<style scoped>
.btn {
  padding: 4px 8px;
}
</style>
