// fixtures/vue-project/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

interface Props {
  start?: number;
  label?: string;
}

const props = withDefaults(defineProps<Props>(), {
  start: 0,
  label: "increment",
});

const count = ref(props.start);
</script>

<template>
  <div class="counter">
    <span data-testid="count">{{ count }}</span>
    <button type="button" @click="count++">{{ props.label }}</button>
  </div>
</template>

// fixtures/counter.tsx
import React, { useState } from "react";

export function Counter() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <button onClick={() => setCount((c) => c + 1)}>Increment</button>
      <button onClick={() => setCount((c) => c - 1)}>Decrement</button>
      <span data-testid="count">{count}</span>
    </div>
  );
}
