// fixtures/vue-project/Button.vue
<script setup lang="ts">
interface Props {
  label: string;
  variant?: "primary" | "secondary" | "danger";
  disabled?: boolean;
  count?: number;
}

const props = defineProps<Props>();
</script>

<template>
  <button class="btn" :class="props.variant" :disabled="props.disabled">
    {{ props.label }}<span v-if="props.count"> ({{ props.count }})</span>
  </button>
</template>

<style scoped>
.btn {
  padding: 4px 8px;
}
</style>

// fixtures/phase-timings/button.tsx
export interface ButtonProps {
  disabled?: boolean;
  variant?: "primary" | "secondary";
  size?: "sm" | "lg";
}

export function Button({ disabled = false, variant = "primary", size = "sm" }: ButtonProps) {
  return (
    <button type="button" className={`btn btn-${variant} btn-${size}`} disabled={disabled}>
      press
    </button>
  );
}

export default Button;
